run:
  timeout: 5m
  go: '1.23'
  skip-dirs:
    - internal/testutil

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
  disable:
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    settings:
      printf:
        funcs:
          - (github.com/geekxflood/common/logging.Logger).Debug
          - (github.com/geekxflood/common/logging.Logger).Info
          - (github.com/geekxflood/common/logging.Logger).Warn
          - (github.com/geekxflood/common/logging.Logger).Error

  revive:
    confidence: 0.8

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104
      - G304

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unused
    - path: pkg/config/config\.go
      linters:
        - typecheck
    - path: internal/testutil/
      linters:
        - typecheck

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
