run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.23'

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - gosimple       # Suggest code simplifications
    - govet          # Reports suspicious constructs
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Static analysis checks
    - unused         # Check for unused constants, variables, functions
    - gofmt          # Check formatting
    - goimports      # Check import formatting
    - misspell       # Spell checker
    - revive         # Fast, configurable, extensible, flexible linter
    - gosec          # Security-focused linter
    - gocritic       # Opinionated Go linter
    - gocyclo        # Cyclomatic complexity
    - dupl           # Code cloning detection
    - bodyclose      # Check for unclosed HTTP bodies
    - contextcheck   # Check context usage
    - errname        # Check error naming
    - errorlint      # Error wrapping checks
    - exhaustive     # Exhaustiveness checks
    - exportloopref  # Checks for pointers to loop variables
    - goconst        # Repeated strings that could be constants
    - godot          # Check if comments end in period
    - nilerr         # Check nil error returns
    - nolintlint     # Ill-formed nolint directives
    - predeclared    # Find shadowing of predeclared identifiers
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Unused function parameters
    - whitespace     # Unnecessary whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked - handled by errcheck
      - G304  # File path provided as taint input - needed for config loading

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude generated code
    - path: internal/models/
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
